version: '3.9'

services:
  api:
    build: ./backend
    container_name: taskflow_api
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://divya_db_user:VdTNTOBoLk0N48Jn@cluster0.98at1vf.mongodb.net/taskflow-api?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=7d
      - ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - taskflow_net

  mongo:
    image: mongo:7
    container_name: taskflow_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taskflow_net

  redis:
    image: redis:7-alpine
    container_name: taskflow_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taskflow_net

volumes:
  mongo_data:

networks:
  taskflow_net:
    driver: bridge
